R/latex.s
man/format.df.Rd

The "..." argument of format.df is no longer ignored, but included in
the definition of formt() and passed to format(). The help file has also
been updated and the example modified to show an example of big.mark.

format.df - passing "..."

---

R/Misc.s

There is a subtle difference between the two approaches, e.g. see https://github.com/yihui/knitr/issues/610

Use suppressWarnings() instead of options(warn=-1)

---

R/dates.s

Note that yday is 0-based, unlike mday.

Fix bug in yearDays

---

R/consolidate.s

I changed "consolidate<-" to call directly to "consolidate". I've checked this with CRAN/BIOC packages that use Hmisc (yet in an older version of Hmisc) and it seems to be working fine. Also Hmisc check seems fine.
The reason for this is to avoid "eval" in the parent frame of the same call, obtained by "match.call". This original approach does not work with the byte-code compiler, which does not create the '*tmp*' temporary variable for assignment calls, but only a pre-evaluated promise with '*tmp*' given as expression in that promise. Ideally R programs should not rely on implementation details of the assignment calls, which are subject to change; in particular, the implementation in the interpreter may soon be modified to match the one in the compiler, which is more robust in complex …

Simplified consolidate<- to work with byte-code compiler

---

R/misc.get.s
man/spss.get.Rd

Currently, `spss.get` does not provide a means for setting the `reencode` parameter of `read.spss` from `foreign`. This causes character encoding issues when loading an UTF-8 encoded SPSS file on Windows. 
This fix solves said issue, allowing users to specify the charset to convert from.

Add 'reencode' parameter to spss.get

---

R/minor.tick.s
man/minor.tick.Rd

I came across this package as a recommendation to put minor tick marks on axes at [http://www.statmethods.net/advgraphs/axes.html]. I found `minor.ticks()` great, but my graphs needed a little more customization. I noticed that this could easily be implemented, by adding two more optional arguments, one for each axis. I implemented these minor changes and updated the documentation in my fork, here I suggest to pull these changes, because it adds functionality without the expense of breaking compatibility.
_For future versions_
I also propose here an alternative to the `minor.tick()` function, which would essentially implement the interface that `axis()` and `axTicks()` use. To avoid confusion and retain compatibility I propose the name `add.minor()` and it could be called as follows …

Support for argument pass through for axis()

---

R/upData.s

NA's appear to be handled incorrectly cleanup.import when called with charfactor, creating a NA level in the new factor if the underlying character vector has NAs.  This creates unexpected behavior in the resulting factors. Example:
```r
dx <- data.frame(x = c("A", NA, NA, "B", "A", "A", "B"), stringsAsFactors = FALSE)
cx <- cleanup.import(dx, charfactor = TRUE)
levels(cx$x)
table(cx$x)  # should need option useNA to display the NA's
```
New behavior adds NA to the exclude.

Fix NA handling cleanup.import with charfactor

---

R/capitalize.s

Previously, the example returned:
```{r}
capitalize(c("Hello", "bob", "daN"))
```
The capital `N` in `daN` seemed to be problematic. 
The desired behaviour should now be:
```{r}
capitalize(c("Hello", "bob", "daN"))
```

did not work when letters after the first had capitals

---

R/ynbind.s

I made a change to R where `factor()` uses `order()` instead of `sort.list()` when generating the levels. Thus, `table(pBlock)` ends up calling `rank()`, which does `x[!nas]` and `[.pBlock` yields an invalid object, since the result is a vector, not a matrix. That causes problems later.
This change makes it so `[.pBlock` just returns a vector when the result of the call to base `[` is not a matrix.

[.pBlock() only retains the pBlock class if the result is a matrix

---

R/latex.s

Currently, when `latex.summary.formula.reverse()` has multiple items in its legend (e.g., when test = TRUE and there are categorical and continuous variables present), these are pasted together without spaces. For example: "the upper quartile $c$\ for continuous variables.Numbers after percents are frequencies" (note, no space after the end of the first sentence).
Reproducible example:
```
library(Hmisc)
test <- data.frame(a = 1:50, b = rep(c('a', 'b'), 25), c = rep(c('c', 'd'), 25))
latex(summary(b ~ a + c, data = test, method = 'reverse', test = TRUE), file = "")
```
This pull request modifies `latex.default()` to `paste()` together the entries with `collapse = ' '`. Another possibility would be to modify `latex.summary.formula.reverse()` to collapse the legend before calling …

insert spaces between multiple entries in bottom index in latex tables

---

R/summary.formula.s
R/summaryM.s

Both latex.summary.formula.reverse() and latex.summaryM() use sedit() to replace ampersands in labels with "\&" and then call latexTranslate(), which replaces the ampersand again, resulting in "\\&" (backslash-backslash-ampersand) being written to the LaTeX output, i.e., an escaped backslash and an unescaped ampersand, causing an error.
This pull request eliminates the unnecessary first replacement of the ampersand, keeping the call to latexTranslate(), which is sufficient.

fix double replacement of ampersand in latex.summary.formula.reverse() and latex.summaryM()

---

R/cut2.s
man/cut2.Rd

Following my conversation with Pr. Harrell by email
```
Z <- 1000*stats::rnorm(10000)
table(cut2(Z, g=4))
table(cut2(Z, g=4, trim = TRUE))
table(cut2(Z, g=4, formatfun = formatC))
table(cut2(Z, g=4, formatfun = signif, digits=1))
table(cut2(Z, g=4, formatfun = function(x) paste0("$",round(x))))
```
I included support for the formula notation if `rlang `is installed, it fails explicitly if users try to use formula notation and and `rlang `is not installed. I can easily remove it.
```
table(cut2(Z, g=4, formatfun = ~paste0("$",signif(.))))
```
My initial reason for this was to be able to use my function `format_metric` :
```
devtools::install_github("moodymudskipper/cutr")
table(cut2(Z, g=4, formatfun = cutr::format_metric)
```
My package uses the argument `format_fun` in its functions but …

implemented formatfun functionality in `cut2`

---

R/latex.s

Added conditional logic in latex.s to appropriately set end of group operators when using the combination of `ctable` and `booktabs`.

Fix midrules for booktabs with ctable Fixes #99

---

R/upData.s

This prevents an error when adding a variable with a single value and subset leaves 0 rows in the object

Manually repeat length-1 values added to object

---

R/Misc.s
R/combplotp.r
R/dotchart3.s
R/dotchartpl.s
R/fit.mult.impute.s
R/gbayesSeqSim.r
R/ggplotlyr.r
R/histSpikeg.s
R/multLines.s
R/panel.bpplot.s
R/plot.describe.s
R/plotlyM.r
R/popower.s
R/rcspline.plot.s
R/sas.get.s
R/scat1d.s
R/simMarkovOrd.r
R/stat-plsmo.r
R/summary.formula.s
R/summaryM.s
R/tabulr.s
R/transace.s
man/combplotp.Rd
man/estSeqSim.Rd
man/multLines.Rd

This PR adds tests for the presence of the suggested packages.  Only a couple of the examples made use of them; those examples have been made conditional.  The functions themselves generally have a call like
if (!requireNamespace("tables", quietly = TRUE))
stop("This function requires the 'tables' package.")
early in the function call so that the problem is clear to the user.  
This PR is motivated by this thread: https://stat.ethz.ch/pipermail/r-package-devel/2021q2/007101.html, where a (hopefully temporary) lack of plotly on a platform prevented Hmisc from installing there.

Test for usage of suggested packages. 

---

R/mdb.get.s

Reading Microsoft Access database files via `mdb.get()` works fine for me **on FreeBSD** without any problems for years now. Many thanks for the nice package!
Now my team at work also has to read mdb files directly (without an odbc connection) **on Windows 10**. Reading mdb files and tables directly on the command line works fine with installed **MDBTools** [1] under Windows 10 (64 bit), i.e. `mdb-export -b strip d:\path\to\mdb.file TABLE`. So the needed underlying tools are present and usable.
In a next step we tried the same R scripts we are using on Unix to read the mdb files. It turns out, that `mdb.get()` from Hmisc is not able to read tables from the mdb files under Windows 10 at all(?). In all our trials, table queries returned without reading in any data.
After investigating a bit …

Fix for mdb.get() on Windows

---

R/summary.formula.s

Hi Frank, 
This commit fixes an error associated with the prN=TRUE argument when latex'ing the result of summaryM:
```
> latex(summaryM(Petal.Width ~ Species, data=iris), prN=TRUE, file="")
Error in math("N=", cqu[j, ncol(cqu)]) : 
unused argument (cqu[j, ncol(cqu)])
>  latex(summaryM(Petal.Width ~ Species, data=iris), prN=TRUE, file="")
%latex.default(cstats, title = title, file = file, append = TRUE,     caption = finalcaption, rowlabel = rowlabel, table.env = (!tabenv1 &&         table.env) || (tabenv1 && istr == 1), col.just = col.just,     numeric.dollar = FALSE, insert.bottom = finallegend, rowname = lab,     dcolumn = dcolumn, extracolheads = extracolheads, extracolsize = NNsize,     insert.top = if (strat != ".ALL.") strat, ...)%
\begin{table}[!tbp]
\caption{Descriptive …
```

fixes unused argument error in formatCons

---

R/rcspline.restate.s

rcspline.restate was not outputting an addition sign if the coefficients were exactly equal to 0.

Fix rcspline.restate not handling coef[i]==0 correctly

---

R/mdb.get.s

mdb-schema seems to be returning table names wrapped in brackets. This removes the brackets.

Remove brackets

---

R/fit.mult.impute.s

Allow to call `fit.mult.impute` with `fit.reps=T` without explicit `n.impute`

---

R/describe.s

I'm not certain on how the output should be formatted, but this should support issue #193.
This is what plain text output would look like with the change:
```
> Hmisc::describe(paste("long long long long long variable name", letters[1:10]), listunique = 20)
paste("long long long long long variable name", letters[1:10]) 
n  missing distinct 
10        0       10 
lowest : long long long long long variable name a long long long long long variable name b long long long long long variable name c long long long long long variable name d long long long long long variable name e
highest: long long long long long variable name f long long long long long variable name g long long long long long variable name h long long long long long variable name i long long long long long variable name j
long …
```

include proportion when describe creates table values

---

man/windows/sas.get.Rd

The windows and linux documentation help page of sas.get.Rd differ on the alias they use.
This patch unifies that by adding the alias to windows. 
Not totally sure why this is the only difference (I expected a difference on the text but I couldn't find any).
This could also be resolved by moving either of the help files to the main `man/` directory (and deleting the other file).
Here there is a minimal patch to add the alias to the windows file.

unix and windows sas.get.Rd
